services:
  nginx:
    build:
      context: .
      target: nginx
    ports:
      - 80:80
    volumes:
      - files:/var/www/html/files

  omeka-s:
    build:
      context: .
      target: php-fpm
    environment:
      APPLICATION_ENV: development
      DATABASE_USER: omeka
      DATABASE_PASSWORD: omeka
      DATABASE_NAME: omeka
      DATABASE_HOST: database
    volumes:
      - files:/var/www/html/files

  database:
    image: mariadb:10.6.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  files:
